name: build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.12'
      - run: go version
      - name: Install swagger
        run: |
          URL="https://github.com/go-swagger/go-swagger/releases/download/v0.25.0/swagger_linux_amd64"
          curl -o "$HOME/.local/bin/swagger" -L'#' "$URL"
          chmod +x "$HOME/.local/bin/swagger"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Build it all
        run: |
          cd integration-tests
          make build-go
